wyshynav_front_homepage:
    path:     /hello/{name}
    defaults: { _controller: wyshynavFrontBundle:Default:index }

wyshynav_front_home:
    path:     /
    defaults: { _controller: wyshynavFrontBundle:Default:index }

wyshynav_front_login:
    path:     /login
    defaults: { _controller: wyshynavFrontBundle:Default:login }
    
wyshynav_front_Contact:
    path:     /contact
    defaults: { _controller: wyshynavFrontBundle:Default:Contact }
