services:
    fos_user.doctrine_registry:
        alias: doctrine
    app.provider.oauth:
        class: wyshy\UserBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]
        
    