
homepage:
    pattern:   /
    defaults:  { _controller: FOSUserBundle:Security:login }
    
wyshy_user:
    resource: "@wyshyUserBundle/Resources/config/routing.yml"
    prefix:   /

wyshyback_nav:
    resource: "@wyshybackNavBundle/Resources/config/routing.yml"
    prefix:   /back

wyshynav_front:
    resource: "@wyshynavFrontBundle/Resources/config/routing.yml"
    prefix:   /front


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
 
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /log
