wyshy_user:
    resource: "@wyshyUserBundle/Resources/config/routing.yml"
    prefix:   /

wyshyback_nav:
    resource: "@wyshybackNavBundle/Resources/config/routing.yml"
    prefix:   /back

wyshynav_front:
    resource: "@wyshynavFrontBundle/Resources/config/routing.yml"
    prefix:   /front


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
