services:
    redirect.after.login:         
        class: wyshy\UserBundle\Redirection\AfterLoginRedirection        
        arguments: [@router]  

security: 
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext 
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_MEMBRE: ROLE_MEMBRE
        ROLE_MEDECIN: ROLE_MEDECIN
        ROLE_ARBITRE: ROLE_ARBITRE
        ROLE_RESPONSABLE: ROLE_RESPONSABLE
        ROLE_JOUEUR: ROLE_JOUEUR
        ROLE_SUPER_ADMIN: ROLE_ADMIN 
#        
    providers: 
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
    firewalls: 
        main: 
            pattern: ^/ 
            form_login: 
                provider: fos_userbundle 
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
                failure_path:   /front
           
            logout:        
                path:  /logout
                target: /login
            anonymous:     true
         
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/profile/, role: ROLE_USER }
        - { path: ^/affichage, role: ROLE_MEMBRE }
#