services:
    redirect.after.login:         
        class: wyshy\UserBundle\Redirection\AfterLoginRedirection        
        arguments: [@router]  

security: 
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512 
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_MEMBRE: ROLE_MEMBRE
        ROLE_MEDECIN: ROLE_MEDECIN
        ROLE_ARBITRE: ROLE_ARBITRE
        ROLE_RESPONSABLE: ROLE_RESPONSABLE
        ROLE_JOUEUR: ROLE_JOUEUR
        ROLE_SUPER_ADMIN: ROLE_ADMIN 
#        
    providers: 
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
    firewalls: 
        main: 
            pattern: ^/ 
            form_login: 
                provider: fos_userbundle 
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
                failure_path:   /front
            
           
            logout:        
                path:  /logout
                target: /login
            anonymous:     true
            
            oauth:
                failure_path: /login
                login_path: /login
                check_path: /connect_check
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                oauth_user_provider:
                    service: app.provider.oauth
                success_handler: redirect.after.login
           
                    
            logout:       true
            anonymous:    true

            
         
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/profile/, role: ROLE_USER }
        - { path: ^/affichage, role: ROLE_MEMBRE }
#