<?php

namespace Proxies\__CG__\wyshy\backNavBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dossiermedical extends \wyshy\backNavBundle\Entity\Dossiermedical implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'iddossier', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'taille', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'fumeur', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'poid', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'commentaire', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'situation', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'nbenfant', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'nomprenompere', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'nomprenommere', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'maladie', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'datederniervisite', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'raisonvisite', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'sang', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'Test', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'Personne'];
        }

        return ['__isInitialized__', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'iddossier', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'taille', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'fumeur', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'poid', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'commentaire', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'situation', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'nbenfant', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'nomprenompere', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'nomprenommere', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'maladie', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'datederniervisite', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'raisonvisite', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'sang', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'Test', '' . "\0" . 'wyshy\\backNavBundle\\Entity\\Dossiermedical' . "\0" . 'Personne'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dossiermedical $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIddossier()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIddossier();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIddossier', []);

        return parent::getIddossier();
    }

    /**
     * {@inheritDoc}
     */
    public function getTaille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaille', []);

        return parent::getTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function getFumeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFumeur', []);

        return parent::getFumeur();
    }

    /**
     * {@inheritDoc}
     */
    public function getPoid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoid', []);

        return parent::getPoid();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function getSituation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituation', []);

        return parent::getSituation();
    }

    /**
     * {@inheritDoc}
     */
    public function getNbenfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbenfant', []);

        return parent::getNbenfant();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomprenompere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomprenompere', []);

        return parent::getNomprenompere();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomprenommere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomprenommere', []);

        return parent::getNomprenommere();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaladie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaladie', []);

        return parent::getMaladie();
    }

    /**
     * {@inheritDoc}
     */
    public function getDatederniervisite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatederniervisite', []);

        return parent::getDatederniervisite();
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonvisite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonvisite', []);

        return parent::getRaisonvisite();
    }

    /**
     * {@inheritDoc}
     */
    public function getSang()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSang', []);

        return parent::getSang();
    }

    /**
     * {@inheritDoc}
     */
    public function getTest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTest', []);

        return parent::getTest();
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonne', []);

        return parent::getPersonne();
    }

    /**
     * {@inheritDoc}
     */
    public function setIddossier($iddossier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIddossier', [$iddossier]);

        return parent::setIddossier($iddossier);
    }

    /**
     * {@inheritDoc}
     */
    public function setTaille($taille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaille', [$taille]);

        return parent::setTaille($taille);
    }

    /**
     * {@inheritDoc}
     */
    public function setFumeur($fumeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFumeur', [$fumeur]);

        return parent::setFumeur($fumeur);
    }

    /**
     * {@inheritDoc}
     */
    public function setPoid($poid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoid', [$poid]);

        return parent::setPoid($poid);
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function setSituation($situation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituation', [$situation]);

        return parent::setSituation($situation);
    }

    /**
     * {@inheritDoc}
     */
    public function setNbenfant($nbenfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbenfant', [$nbenfant]);

        return parent::setNbenfant($nbenfant);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomprenompere($nomprenompere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomprenompere', [$nomprenompere]);

        return parent::setNomprenompere($nomprenompere);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomprenommere($nomprenommere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomprenommere', [$nomprenommere]);

        return parent::setNomprenommere($nomprenommere);
    }

    /**
     * {@inheritDoc}
     */
    public function setMaladie($maladie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaladie', [$maladie]);

        return parent::setMaladie($maladie);
    }

    /**
     * {@inheritDoc}
     */
    public function setDatederniervisite(\DateTime $datederniervisite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatederniervisite', [$datederniervisite]);

        return parent::setDatederniervisite($datederniervisite);
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonvisite($raisonvisite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonvisite', [$raisonvisite]);

        return parent::setRaisonvisite($raisonvisite);
    }

    /**
     * {@inheritDoc}
     */
    public function setSang($sang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSang', [$sang]);

        return parent::setSang($sang);
    }

    /**
     * {@inheritDoc}
     */
    public function setTest($Test)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTest', [$Test]);

        return parent::setTest($Test);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonne($Personne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonne', [$Personne]);

        return parent::setPersonne($Personne);
    }

}
