wyshyback_nav_homepage:
    path:     /hello/{name}
    defaults: { _controller: wyshybackNavBundle:Default:index }
    
wyshyback_nav_1:
    path:     /
    defaults: { _controller: wyshybackNavBundle:Nav:index }

wyshyback_nav_joueur:
    path:     /joueur
    defaults: { _controller: wyshybackNavBundle:Nav:joueur }
    
wyshyback_nav_ajouterjoueur:
    path:     /ajouterjoueur
    defaults: { _controller: wyshybackNavBundle:Nav:ajouterjoueur }
    
wyshyback_nav_modifierjoueur:
    path:     /modifierjoueur/{idpersonne}
    defaults: { _controller: wyshybackNavBundle:Joueur:modifierjoueur }
    
wyshyback_nav_supprimerjoueur:
    path:     /supprimerjoueur/{idpersonne}
    defaults: { _controller: wyshybackNavBundle:Joueur:supprimerjoueur }
    
wyshyback_nav_addjoueurtodb:
    path:     /addplayer
    defaults: { _controller: wyshybackNavBundle:Joueur:addjoueur }
    
wyshyback_nav_listerjoueurs:
    path:     /listerjoueurs
    defaults: { _controller: wyshybackNavBundle:Joueur:affichejoueurs }   
    
#    Debut Routing Chams    
    
tft_addMedecin:
    path:     /addMedecin
    defaults: { _controller: wyshybackNavBundle:Medecin:addMedecin }


tft_listMedecin:
    path:     /listMedecin
    defaults: { _controller: wyshybackNavBundle:Medecin:afficheMedecin }
    
tft_updateMedecin:
    path:     /updateMedecin/{cin}
    defaults: { _controller: wyshybackNavBundle:Medecin:ModifierMedecin }
    
tft_deleteMedecin:
    path:     /deleteMedecin/{cin}
    defaults: { _controller: wyshybackNavBundle:Medecin:deleteMedecin }
    
tft_ajoutEvent:
    path:     /ajoutEvent
    defaults: { _controller: wyshybackNavBundle:Evenement:ajoutEvent }
    
tft_affEvent:
    path:     /affEvent
    defaults: { _controller: wyshybackNavBundle:Evenement:afficheEvent }
    
tft_modifEvent:
    path:     /modifEvent/{id}
    defaults: { _controller: wyshybackNavBundle:Evenement:ModifierEvent }
    
    
tft_deleteEvent:
    path:     /suppEvent/{id}
    defaults: { _controller: wyshybackNavBundle:Evenement:deleteEvent }
    
tft_ajoutCompte:
    path:     /addCompteMed
    defaults: { _controller: wyshybackNavBundle:CompteRendu:ajoutCompte }
    
tft_ajoutCompteMatch:
    path:     /addCompteMatch
    defaults: { _controller: wyshybackNavBundle:CompteRenduMatch:ajout }
    
tft_ajoutActu:
    path:     /addActu
    defaults: { _controller: wyshybackNavBundle:Actualite:ajouter }
    
tft_affActu:
    path:     /affActu
    defaults: { _controller: wyshybackNavBundle:Actualite:afficheActualite }

    
tft_modifactu:
    path:     /modifActu/{id}
    defaults: { _controller: wyshybackNavBundle:Actualite:ModifierActu }    
    
tft_deleteactu:
    path:     /suppactu/{id}
    defaults: { _controller: wyshybackNavBundle:Actualite:deleteActu }
    
tft_affcompte:
    path:     /affcompte
    defaults: { _controller: wyshybackNavBundle:CompteRendu:affiche }
    
tft_suppcompte:
    path:     /suppcompte/{id}
    defaults: { _controller: wyshybackNavBundle:CompteRendu:delete }


tft_ajoutVid:
    path:     /addVid
    defaults: { _controller: wyshybackNavBundle:Video:ajoutVideo }
    
tft_affVideo:
    path:     /affVid
    defaults: { _controller: wyshybackNavBundle:Video:afficherVideo }    
    
tft_modifVideo:
    path:     /modifVideo/{id}
    defaults: { _controller: wyshybackNavBundle:Video:ModifierVideo }    

tft_affActuFront:
    path:     /affActufront
    defaults: { _controller: wyshybackNavBundle:Actualite:afficheactufront }
    
    
tft_suppVideo:
    path:     /suppVid/{id}
    defaults: { _controller: wyshybackNavBundle:Video:deleteVideo }    
    
tft_DetailsActu:
    path:     /detailActu/{idactualite}
    defaults: { _controller: wyshybackNavBundle:Actualite:detailActu }
    
tft_affVidFront:
    path:     /affVidfront
    defaults: { _controller: wyshybackNavBundle:Video:afficherVideoFront }    
    
       
#    Fin Routing Chams    

#    ----------------------------------------------------------    


#    Debut Routing  Wissem    


wyshyback_maptft:
    path:     /maptft
    defaults: { _controller: wyshybackNavBundle:Default:tftmap}

tft_addStade:
    path:     /addStade
    defaults: { _controller: wyshybackNavBundle:Stade:addStade }
    
    
tft_updateStade:
    path:     /updateStade/{libellestade}
    defaults: { _controller: wyshybackNavBundle:Stade:ModifierStade }

tft_deleteStade:
    path:     /deleteStade/{idstade}
    defaults: { _controller: wyshybackNavBundle:Stade:deleteStade }
    
tft_findStade:
    path:     /listStade
    defaults: { _controller: wyshybackNavBundle:Stade:rechercherStade }
    
tft_LocaliserStade:
    path:     /mapStade/{idstade}
    defaults: { _controller: wyshybackNavBundle:Stade:LocaliserStade }    

tft_ListerMembres:
    path:     /ListerMembres
    defaults: { _controller: wyshybackNavBundle:Membres:afficheMembres } 

tft_BloquerMembres:
    path:     /BloquerMembre/{id}
    defaults: { _controller: wyshybackNavBundle:Membres:BloquerMembres } 
    
tft_DeBloquerMembres:
    path:     /DeBloquerMembre/{id}
    defaults: { _controller: wyshybackNavBundle:Membres:DeBloquerMembres }

tft_AddTestDopage:
    path:     /AddTestDopage
    defaults: { _controller: wyshybackNavBundle:TestDopage:addTestDopage }
    
tft_ListePlayersTest:
    path:     /PlayersTestDopage
    defaults: { _controller: wyshybackNavBundle:TestDopage:affichePlayers }

    
tft_ListeTestDopages:
    path:     /ListeTestDopage
    defaults: { _controller: wyshybackNavBundle:TestDopage:afficheTestDopage }

tft_deletTestDopages:
    path:     /deleteTestDopage/{id}
    defaults: { _controller: wyshybackNavBundle:TestDopage:deleteTestDopage }

tft_UpdateTestDopages:
    path:     /updateTestDopage/{id}
    defaults: { _controller: wyshybackNavBundle:TestDopage:ModifierTest }

tft_InviterPlayerTest:
    path:     /inviter
    defaults: { _controller: wyshybackNavBundle:TestDopage:inviterJoueurs }

_grapheChartLine:
    path:     /chartLine
    defaults: { _controller: wyshybackNavBundle:Graphe:chartLine } 
    
_grapheHistogramme:
    path:     /histogramme
    defaults: { _controller: wyshybackNavBundle:Graphe:chartHistogramme }    
 
_graphePie:
    path:     /pie
    defaults: { _controller: wyshybackNavBundle:Graphe:chartPie }

_graphePie2:
    path:     /pie2
    defaults: { _controller: wyshybackNavBundle:Graphe:chartPie2 }

_graphePie3:
    path:     /pie3
    defaults: { _controller: wyshybackNavBundle:Graphe:chartPie3 }

tft_addDossier:
    path:     /addDossier
    defaults: { _controller: wyshybackNavBundle:DossierMedical:addDossier }

tft_ListerDossier:
    path:     /ListeDossier
    defaults: { _controller: wyshybackNavBundle:DossierMedical:afficheDossierMedical }

tft_DeleteDossier:
    path:     /deleteDossier/{iddossier}
    defaults: { _controller: wyshybackNavBundle:DossierMedical:supprimerDossier }

tft_UpdateDossier:
    path:     /UpdateDossier/{iddossier}
    defaults: { _controller: wyshybackNavBundle:DossierMedical:ModifierDossier }

tft_DetailsDossier:
    path:     /DetailsDossier/{iddossier}
    defaults: { _controller: wyshybackNavBundle:DossierMedical:DetailsDossier }

tft_Mail:
    path:     /mail
    defaults: { _controller: wyshybackNavBundle:Contact:mail }
    
#    Fin Routing Wissem

#    -----------------------------------------------------------------    

    