<?php

namespace wyshy\backNavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends EntityRepository

{
 public function findByRole($role)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.role like :joueur  ')
                    ->setParameter('joueur', $role);
        return $qb->getQuery()->getResult();
    }
    
    
    
 public function deletePlayer($idpersonne){
     
     $qb = $this->createQueryBuilder('personne')
             ->update('personne')
             ->set('personne.datedestruction', 'now()')
             ->where('personne.idpersonne like :joueur')
             ->setParameter('joueur', $idpersonne);
      return $qb->getQuery();
 }
}