<?php

namespace wyshy\backNavBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadeRepository extends EntityRepository

{
 public function findByNom($libelle)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.libellestade like :libelle  ')
                    ->orderBy('u.libellestade')
                    ->setParameter('libelle', $libelle);
        return $qb->getQuery()->getResult();
    }
}